= Camel Demo API Guide
David Lewis;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
= Overview

[[overview-http-verbs]]
== HTTP verbs

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview-http-status-codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

[[overview-headers]]
== Headers

Every response has the following header(s):


[[overview-errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object
that describes the problem. The error object has the following structure:


For example, a request that attempts to apply a non-existent tag to a note will produce a
`400 Bad Request` response:



[[routes]]
= Routes

[[routes-list]]
== List Camel Routes

List all the available Camel routes.  The list shows the route identifier and the current status.

operation::routes-list[snippets='curl-request,http-response,response-fields']

[[routes-start]]
== Start Camel route

Starts the Camel route.

operation::routes-start[snippets='curl-request,path-parameters,http-response,response-fields']

[[routes-stop]]
== Stop Camel route

Stops the Camel route.

operation::routes-stop[snippets='curl-request,path-parameters,http-response,response-fields']

[[events]]
= Events

[[events-list]]
== List the event log

List all the available events. 

operation::events-list[snippets='curl-request,http-response,response-fields']
